version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit_message:
      prefix: chore
      include_scope: true

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit_message:
      prefix: chore
      include_scope: true

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
