substitutions:
  _SERVICE_NAME: payments-service

steps:
  # Step 1: Generate from Protobuf
  # - name: bufbuild/buf@sha256:d104e96432a276ee21eaa2c905c22c81c6ebb3a5ffb0750332f91930a426858e
  #   args:
  #     - generate

  # Step 2: Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel:7.0.1@sha256:88cc8c1fb9ca63c08f1f4b47f5ad475bdd3bcc532a07006d9550b2ac078deaed
    id: build
    args:
      [
        run,
        //cmd/api-server:container,
        --remote_cache=https://storage.googleapis.com/$_BAZEL_REMOTE_CACHE_BUCKET,
        --google_default_credentials,
      ]

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:a1317a0b68260d87488f1fcd87518db39bcda42eee79f405b3f07d2cb98f3da7
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:a1317a0b68260d87488f1fcd87518db39bcda42eee79f405b3f07d2cb98f3da7
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:a1317a0b68260d87488f1fcd87518db39bcda42eee79f405b3f07d2cb98f3da7
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 4: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:a1317a0b68260d87488f1fcd87518db39bcda42eee79f405b3f07d2cb98f3da7
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Test the image.
  - name: gcr.io/gcp-runtimes/container-structure-test@sha256:377f9a9bc00376b9fa6dc6a3a020dbe40e84ebe9481b71969aa3ff9d1c9ea17e
    id: test
    args:
      [
        test,
        --image,
        asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA,
        --config,
        cmd/api-server/container_structure_test.yaml,
      ]

  # Step 5: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:f39c0611c6fc91ab7081b1c385061f884c222ec917c6ad0cd3010f035ec9a9aa
    waitFor:
        - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,WALLET_SERVICE_HOST=$_WALLET_SERVICE_HOST
      - --update-secrets=RAZORPAY_KEY=razorpay-key:latest,RAZORPAY_SECRET=razorpay-secret:latest,RAZORPAY_ACCOUNT_NUMBER=razorpay-account-number:latest
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
