substitutions:
  _SERVICE_NAME: wallet-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:710a55e0f91ef56ef343f33c9035b4755b24d5ff718f521dd19a93371c15004a
    args:
      - generate

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:04d3d2b37d601c423f4ccc054f02a7bf0ecc7ef9e12737b554c385067e99b214
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:04d3d2b37d601c423f4ccc054f02a7bf0ecc7ef9e12737b554c385067e99b214
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:9240181decda54e9f46627cc778bc679541f2eed0b5b1f06b04025b30b1d4e38
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --update-secrets=RAZORPAY_KEY=razorpay-key:latest,RAZORPAY_SECRET=razorpay-secret:latest,RAZORPAY_ACCOUNT_NUMBER=razorpay-account-number:latest
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
