substitutions:
  _SERVICE_NAME: payments-service

steps:
  # Build Docker image
  - name: gcr.io/cloud-builders/docker@sha256:9d9c650dc3573da1b0629b36e6310d169c8fed1ab911a959ff6785a98da2ebb1
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - .

  # Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:9d9c650dc3573da1b0629b36e6310d169c8fed1ab911a959ff6785a98da2ebb1
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:5ef18ee4e18da93486c080791a6e0285c76eaac63a3c8079c37ca7ec21669674
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --update-secrets=RAZORPAY_KEY=razorpay-key:latest,RAZORPAY_SECRET=razorpay-secret:latest,RAZORPAY_ACCOUNT_NUMBER=razorpay-account-number:latest
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
