name: payments-service
runtime: nodejs
description: A minimal Google Cloud TypeScript Pulumi program
config:
  gcp:region: asia-east1
  service:name: payments-service
  pulumi:tags:
    value:
      pulumi:template: gcp-typescript
