// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ride/payments/v1alpha1/recharge.proto

package paymentsv1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Recharge with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Recharge) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Recharge with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RechargeMultiError, or nil
// if none found.
func (m *Recharge) ValidateAll() error {
	return m.validate(true)
}

func (m *Recharge) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetName() != "" {

		if !_Recharge_Name_Pattern.MatchString(m.GetName()) {
			err := RechargeValidationError{
				field:  "Name",
				reason: "value does not match regex pattern \"^users/[A-Za-z0-9_-]+/wallet/recharges/[A-Za-z0-9_-]+$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetAmount() <= 0 {
		err := RechargeValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _Recharge_Status_NotInLookup[m.GetStatus()]; ok {
		err := RechargeValidationError{
			field:  "Status",
			reason: "value must not be in list [STATUS_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCreateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RechargeValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RechargeValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RechargeValidationError{
				field:  "CreateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RechargeValidationError{
					field:  "UpdateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RechargeValidationError{
					field:  "UpdateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RechargeValidationError{
				field:  "UpdateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	switch v := m.Metadata.(type) {
	case *Recharge_TransactionId:
		if v == nil {
			err := RechargeValidationError{
				field:  "Metadata",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for TransactionId
	case *Recharge_FailureReason:
		if v == nil {
			err := RechargeValidationError{
				field:  "Metadata",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for FailureReason
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return RechargeMultiError(errors)
	}

	return nil
}

// RechargeMultiError is an error wrapping multiple validation errors returned
// by Recharge.ValidateAll() if the designated constraints aren't met.
type RechargeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RechargeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RechargeMultiError) AllErrors() []error { return m }

// RechargeValidationError is the validation error returned by
// Recharge.Validate if the designated constraints aren't met.
type RechargeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RechargeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RechargeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RechargeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RechargeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RechargeValidationError) ErrorName() string { return "RechargeValidationError" }

// Error satisfies the builtin error interface
func (e RechargeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRecharge.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RechargeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RechargeValidationError{}

var _Recharge_Name_Pattern = regexp.MustCompile("^users/[A-Za-z0-9_-]+/wallet/recharges/[A-Za-z0-9_-]+$")

var _Recharge_Status_NotInLookup = map[Recharge_Status]struct{}{
	0: {},
}
