// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ride-app/payments-service/internal/repositories/payout (interfaces: PayoutRepository)

// Package mock_payout is a generated GoMock package.
package mock_payout

import (
	context "context"
	reflect "reflect"
	time "time"

	logger "github.com/dragonfish/go/v2/pkg/logger"
	gomock "github.com/golang/mock/gomock"
	paymentsv1alpha1 "github.com/ride-app/payments-service/api/ride/payments/v1alpha1"
)

// MockPayoutRepository is a mock of PayoutRepository interface.
type MockPayoutRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPayoutRepositoryMockRecorder
}

// MockPayoutRepositoryMockRecorder is the mock recorder for MockPayoutRepository.
type MockPayoutRepositoryMockRecorder struct {
	mock *MockPayoutRepository
}

// NewMockPayoutRepository creates a new mock instance.
func NewMockPayoutRepository(ctrl *gomock.Controller) *MockPayoutRepository {
	mock := &MockPayoutRepository{ctrl: ctrl}
	mock.recorder = &MockPayoutRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayoutRepository) EXPECT() *MockPayoutRepositoryMockRecorder {
	return m.recorder
}

// CancelPayout mocks base method.
func (m *MockPayoutRepository) CancelPayout(arg0 context.Context, arg1 logger.Logger, arg2 string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPayout", arg0, arg1, arg2)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelPayout indicates an expected call of CancelPayout.
func (mr *MockPayoutRepositoryMockRecorder) CancelPayout(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPayout", reflect.TypeOf((*MockPayoutRepository)(nil).CancelPayout), arg0, arg1, arg2)
}

// CreatePayout mocks base method.
func (m *MockPayoutRepository) CreatePayout(arg0 context.Context, arg1 logger.Logger, arg2 *paymentsv1alpha1.PayoutAccount, arg3 *paymentsv1alpha1.Payout) (*paymentsv1alpha1.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayout", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*paymentsv1alpha1.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayout indicates an expected call of CreatePayout.
func (mr *MockPayoutRepositoryMockRecorder) CreatePayout(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayout", reflect.TypeOf((*MockPayoutRepository)(nil).CreatePayout), arg0, arg1, arg2, arg3)
}

// CreatePayoutAccount mocks base method.
func (m *MockPayoutRepository) CreatePayoutAccount(arg0 context.Context, arg1 logger.Logger, arg2 string, arg3 *paymentsv1alpha1.PayoutAccount) (*paymentsv1alpha1.PayoutAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayoutAccount", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*paymentsv1alpha1.PayoutAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayoutAccount indicates an expected call of CreatePayoutAccount.
func (mr *MockPayoutRepositoryMockRecorder) CreatePayoutAccount(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayoutAccount", reflect.TypeOf((*MockPayoutRepository)(nil).CreatePayoutAccount), arg0, arg1, arg2, arg3)
}

// GetPayout mocks base method.
func (m *MockPayoutRepository) GetPayout(arg0 context.Context, arg1 logger.Logger, arg2, arg3 string) (*paymentsv1alpha1.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayout", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*paymentsv1alpha1.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayout indicates an expected call of GetPayout.
func (mr *MockPayoutRepositoryMockRecorder) GetPayout(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayout", reflect.TypeOf((*MockPayoutRepository)(nil).GetPayout), arg0, arg1, arg2, arg3)
}

// GetPayoutAccount mocks base method.
func (m *MockPayoutRepository) GetPayoutAccount(arg0 context.Context, arg1 logger.Logger, arg2 string) (*paymentsv1alpha1.PayoutAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayoutAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].(*paymentsv1alpha1.PayoutAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayoutAccount indicates an expected call of GetPayoutAccount.
func (mr *MockPayoutRepositoryMockRecorder) GetPayoutAccount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayoutAccount", reflect.TypeOf((*MockPayoutRepository)(nil).GetPayoutAccount), arg0, arg1, arg2)
}

// GetPayouts mocks base method.
func (m *MockPayoutRepository) GetPayouts(arg0 context.Context, arg1 logger.Logger, arg2 string) ([]*paymentsv1alpha1.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayouts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*paymentsv1alpha1.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayouts indicates an expected call of GetPayouts.
func (mr *MockPayoutRepositoryMockRecorder) GetPayouts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayouts", reflect.TypeOf((*MockPayoutRepository)(nil).GetPayouts), arg0, arg1, arg2)
}
