name: Dev

on:
  push:
    branches-ignore:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "17"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: |
            node-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install Packages
        run: npm install

      # - name: Build protobuf types
      #   run: npm run build:proto

      - name: Format
        run: trunk fmt

      - name: Lint
        run: trunk check

      - name: Test
        run: |
          npm run test:api
          npm run test:unit
