name: Dev

on:
  push:
    branches-ignore:
      - main
      - trunk-merge/**

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "17"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: |
            node-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install Packages
        run: npm install

      - name: Lint
        uses: trunk-io/trunk-action@v1

      # - name: Test
      #   run: |
      #     npm run test:api
      #     npm run test:unit
