name: PR

permissions: read-all

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Cache Bazel
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE','MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: |
          bazelisk run //:gazelle-update-repos-go
          bazelisk run //:gazelle
          bazelisk build //...

  compute_impacted_targets:
    uses: dragonfish/workflows/.github/workflows/compute-impacted-targets.yaml@main
    secrets: inherit

  auto_merge:
    permissions:
      contents: read
      pull-requests: write
    name: Auto Merge PR if bot
    uses: dragonfish/workflows/.github/workflows/auto-merge.yaml@main
