name: pr

on:
  pull_request:
    branches:
      - main

env:
  SERVICE_NAME: wallet-service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc

      - name: Cache node_modules
        uses: actions/cache@v2.1.7
        with:
          path: |
            **/node_modules
          key: |
            node-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: Get firebase-tools
        run: npm install -g firebase-tools

      - name: Install Packages
        run: npm install

      - uses: bufbuild/buf-setup-action@v1.4.0
        with:
          github_token: ${{ github.token }}

      - name: Build protobuf
        run: buf generate

      - name: Lint
        uses: trunk-io/trunk-action@v1

      # - name: Test
      #   run: npm test:integration

  # build:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to GHCR
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and Upload
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ghcr.io/${{env.SERVICE_NAME}}:${{github.sha}}
  #         push: true
