name: pr

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    env:
      GOPRIVATE: go.buf.build
      BUF_USER: debkanchan
    permissions:
      checks: write # For trunk to post annotations
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - uses: bufbuild/buf-setup-action@v1.27.2
        with:
          github_token: ${{ github.token }}

      - name: Authenticate buf
        run: echo ${{ secrets.BUF_TOKEN }} | buf registry login --username ${{ env.BUF_USER }} --token-stdin

      - name: Build protobuf
        run: buf generate

      - name: Lint
        uses: trunk-io/trunk-action@v1
